"""add loyalty_discount to Order

Revision ID: 6ac6a28c079c
Revises: c33c09ba0e1e
Create Date: 2024-11-16 18:25:48.019136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac6a28c079c'
down_revision = 'c33c09ba0e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_discount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('loyalty_discount')

    # ### end Alembic commands ###
