"""add loyalty discount to order

Revision ID: 9375f7428bdc
Revises: c33c09ba0e1e
Create Date: 2024-11-18 09:47:29.110535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9375f7428bdc'
down_revision = 'c33c09ba0e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalties', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_discount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('loyalty_discount')

    with op.batch_alter_table('loyalties', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
